$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaries:
  - python
words:
  - pytube
ignorePaths:
  - typings
  - .git
enableGlobDot: true
allowCompoundWords: true
useGitignore: true
